version: '3'
services:
  bingusboingus:
    hostname: bingusboingus
    pull_policy: always
    image: ghcr.io/blvckleg/bingusboingus:dev
    volumes:
      - .env:/home/node/.env.prod
    environment:
      NODE_ENV: prod
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - mongo

  mongo:
    image: mongo:6.0.3
    hostname: mongo
    volumes:
      - ./infra/mongo:/db/data:rw
      - ./infra/mongo/mongo.conf:/etc/mongo/mongo.conf:ro
    env_file:
      - ./infra/mongo/.env
    command:
      - --config
      - /etc/mongo/mongo.conf
    expose:
      - 27017
    healthcheck:
      test:
        [
          'CMD',
          'sh',
          '-c',
          'echo ''db.runCommand("ping").ok'' | mongosh localhost:27017 --quiet'
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    networks:
      - mongo

networks:
  mongo:
    name: mongo
