version: '3'
services:
  bingusboingus:
    hostname: bingusboingus
    image: bingusboingus:latest
    volumes:
      - .env:/home/node/.env.prod
    environment:
      NODE_ENV: prod
    ports:
      - 3000:3000
    restart: unless-stopped

