# TEST DOCKERFILE
FROM node:16-alpine as builder

ENV NODE_ENV build

USER node
WORKDIR /home/node

COPY ./package*.json /home/node/
RUN npm ci

COPY ./src /home/node/src
COPY ./tsconfig.json /home/node/tsconfig.json
COPY ./.prettierrc.json /home/node/.prettierrc.json
COPY --chown=node:node --from=builder /home/node/src/assets/ /home/node/src/assets/

ENTRYPOINT [""]
