# TEST DOCKERFILE
FROM node:22-alpine AS builder

ENV NODE_ENV build

USER node
WORKDIR /home/node

COPY ./package*.json /home/node/
RUN npm ci

COPY ./src /home/node/src
COPY ./tsconfig.json /home/node/tsconfig.json
COPY ./.prettierrc /home/node/.prettierrc
COPY ./.eslintrc.js /home/node/.eslintrc.js

ENTRYPOINT [""]
