name: Deploy

on:
  workflow_run:
    workflows: [Docker Image CI]
    types: [completed]
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script_stop: true
          script: |
            cd bingusboingus
            docker compose pull
            docker compose up -d

###ssh sachen
# https://github.com/appleboy/ssh-action
